name: blox
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: 14.2.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.6
  firebase_core: 3.2.0
  firebase_crashlytics: 4.0.2
  firebase_auth: 5.1.2
  webview_flutter: 4.8.0
  url_launcher: 6.3.0
  image_picker: 1.1.2
  flutter_bloc: 8.1.6
  meta: 1.12.0
  equatable: 2.0.5
  mime: 1.0.5
  video_player: 2.9.1
  font_awesome_flutter: 10.7.0
  fluttertoast: 8.2.6
  image_cropper: 7.1.0
  cloud_firestore: 5.1.0
  timeago: 3.7.0
  scroll_wheel_date_picker: 0.0.2+1
  intl: 0.19.0
  google_sign_in: 6.2.1
  dotted_border: ^2.1.0
  firebase_messaging: ^15.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.0
  build_runner: 2.4.11
  build_verify: 3.1.0
  go_router_builder: 2.7.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/x.png
    - assets/images/x-dark.png
    - assets/images/google.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
